---
- name: Cleanup playbook and reinstall the undercloud
  hosts: localhost
  become: true
  ignore_errors: true
  tasks:
    - name: Remove containers
      command: podman rm -af
      become: true

    - name: Remove container images
      command: podman rmi -af
      become: true

    - name: Remove directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/tripleo-config
        - /var/lib/config-data
        - /var/lib/container-config-scripts
        - /var/lib/container-puppet
        - /var/lib/heat-config
        - /var/lib/image-service
        - /var/lib/mysql
      become: true

    - name: Remove log files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - /home/stack/*.log
      become: true

    - name: Remove tripleo-deploy directory
      file:
        path: /home/stack/tripleo-deploy
        state: absent
      become: true

    - name: Delete br-ctlplane bridge
      command: ovs-vsctl del-br br-ctlplane
      become: true

    - name: Delete network devices
      command: nmcli d delete {{ item }}
      with_items:
        - bond-ctlplane
        - eno3
        - eno4
      become: true

    - name: Remove network scripts
      file:
        path: /etc/sysconfig/network-scripts/{{ item }}
        state: absent
      with_items:
        - ifcfg-*
        - tripleo*
      become: true

    - name: Remove systemd service files
      file:
        path: /etc/systemd/system/{{ item }}
        state: absent
      with_fileglob:
        - tripleo*
      become: true

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
      become: true

    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
      become: true

    -name: Install the undercloud
      command: openstack undercloud install
